# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JmEVBXd/7rhny/adm92Q+LybQLNaikcSRZKyQS1GSwbdKhmxXnKPZ9ctYt2EWkFgeW8+DnwfrZRq1MwvnMyICeZk1bvAyMVBhYVOQ13qRxZezfytnxq5KTrPw/I4ziL5I9dLYKlBkR46F4XAhfdVCXkKpiHhf+NeYgmmwYSCzGqpQRtAx91hLb9wwa+B2XRDPvlKupI76vkojd9CIXNcdrNmfESR8BckXGsQ96AO5Dyy/33/mFLYtIqxbud9CU8piAfv33nF/QtFEYBVu0jhM8Zy1fUfKkF3SVr0wv/OzaDbyG79bBQ7t0FecwBMwa+35sO3axChR806u82u/2vgcJmkLBFn5aZMRtQeAtr5b2DvrZl2Nhj3u6thrTE7/W7y8gLX1r75yoeXdT++HFuQ2HiA7ugx0jvt2U3/WFwunU5YSCOY+BEFhDgZI1tKLeub/V6IBOa/8RwIlFcg6O8Rwg2EhpsjQD5s/urW2wnssoesDkFAk5yawFjY0aOe/MC556JCZStedoNa/b232HC+fiKNYr2WxG5uDyf4zqBdDRTribjs1e+McbyMD00WDubF9jcs7Ur+AYU5NCf8duXmu9T+8RtiRmg9EyPrzvCKfZLn6/R83L970ZW4MgttB/UIZwmTAVb/lzmBm7g5ay92v9Ky1lrGAXA/F1nezAi2Ozw="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
